services:
  stastracker:
    build: .
    env_file:
      - .env
    container_name: stastracker
    expose:
      - "5000"

  haproxy:
    image: haproxy:alpine
    container_name: haproxy
    ports:
      - "80:80"
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - stastracker
